name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3.1.0
      
      - name: Docker login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{  secrets.COMPASS_USER_DOCKERHUB  }}
          password:  ${{  secrets.COMPASS_PASSWORD_DOCKERHUB  }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.10.0]
        with:
          context: .
          file: .
          push: true
          tags: |
            iamgacarvalho/dmc-quality-pipeline-compass:v1
            iamgacarvalho/dmc-quality-pipeline-compass:1.0.0
          


          
